modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="extendedcolors"
version="0.1"
displayName="Extended Colors"
logoFile="examplemod.png"
credits="Extended Colors by HiJiNXeD & One-TK"
authors="HiJiNXeD and One-TK"
description='''
A mod for those who already struggle to find the right color to use.'''
[[dependencies.extendedcolors]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.extendedcolors]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
